#
#   Carbon framework FreeRTOS backend makefile
#
#   Copyright (c) 2018 Softland. All rights reserved.
#   Licensed under the Apache License, Version 2.0
#
#   Revision history:
#
#   Revision 1.0, 03.10.2018
#	Initial revision.
#

DIRS = freertos/Source

include ../tool/multidir.mak

