#
#   Carbon framework examples makefile
#
#   Copyright (c) 2019 Softland. All rights reserved.
#   Licensed under the Apache License, Version 2.0
#
#   Revision history:
#
#   Revision 1.0, 21.12.2019 13:05:39
#	Initial revision
#
#

DIRS := 00empty 01minimal 02event 03timer 04thread 05module \
	06net_server 07remote_event 08shell_execute 09net_sync \
	10net_server_sync 11udp_server     13dns_client

include ../tool/multidir.mak
