#
#   Carbon framework makefile
#
#   Copyright (c) 2018 Softland. All rights reserved.
#   Licensed under the Apache License, Version 2.0
#
#   Revision history:
#
#   Revision 1.0, 03.10.2018
#	Initial revision.
#

include ../tool/config.mak

ifneq ($(CARBON_BACKEND),)
include $(CARBON_BACKEND)/Makefile 
else

all makeall clean makeclean rebuild r:

endif
