#
#   Carbon framework example makefile
#
#   Copyright (c) 2015 Softland. All rights reserved.
#   Licensed under the Apache License, Version 2.0
#
#   Revision history:
#
#   Revision 1.0, 10.06.2015 10:41:44
#	Initial revision.
#
#   make [CROSS_COMPILE=<gcc-prefix>] [RELEASE=1]
#

PROGRAM = shell_execute_app
OBJ = shell_execute_app.o
INCLUDE = shell_execute_app.h

all: carbon_dep $(PROGRAM) Makefile

include ../../tool/pkgrules.mak
