
OBJ += net_media/sdp.o net_media/rtsp_client.o net_media/rtp.o net_media/rtp_frame_cache.o \
	net_media/rtp_receiver_pool.o net_media/rtp_input_queue.o \
	net_media/rtp_playout_buffer.o net_media/media_sink.o net_media/media_client.o \
	net_media/rtsp_channel.o \
	net_media/h264.o net_media/rtp_playout_buffer_h264.o net_media/rtsp_channel_h264.o \
	net_media/rtp_video_h264.o net_media/rtcp.o net_media/rtcp_client.o \
	net_media/rtp_session.o \
	\
	net_media/store/media_file.o net_media/media_frame.o net_media/store/mp4_h264_file.o \
	net_media/store/mp4_h264/h264.o net_media/store/mp4_cache.o net_media/store/mp4_recorder.o \
	\
	net_media/audio/audio_frame.o net_media/audio/audio_sink.o net_media/audio/audio_server.o \
	\
	net_media/subtitle/subtitle_frame.o net_media/subtitle/subtitle_sink.o \
	net_media/subtitle/subtitle_server.o

DEPS += net_media/sdp.h net_media/rtsp_client.h net_media/rtp.h net_media/rtp_frame_cache.h \
	net_media/rtp_receiver_pool.h net_media/rtp_input_queue.h net_media/rtp_playout_buffer.h \
	net_media/media_sink.h net_media/media_client.h net_media/rtsp_channel.h net_media/h264.h \
	net_media/rtp_playout_buffer_h264.h net_media/rtsp_channel_h264.h \
	net_media/rtp_video_h264.h net_media/rtcp.h net_media/rtcp_client.h net_media/rtp_session.h \
	\
	net_media/store/media_file.h net_media/media_frame.h net_media/store/mp4_h264_file.h \
	net_media/store/mp4_h264/mp4av_h264.h net_media/store/mp4_h264/mpeg4ip.h \
	net_media/store/mp4_h264/mpeg4ip_bitstream.h net_media/store/mp4_cache.h \
	net_media/store/mp4_recorder.h \
	\
	net_media/audio/audio_frame.h net_media/audio/audio_sink.h net_media/audio/audio_server.h \
	\
	net_media/subtitle/subtitle_frame.h net_media/subtitle/subtitle_sink.h \
	net_media/subtitle/subtitle_server.h

