
OBJ_embed += embed/tneo/hr_time.o embed/tneo/lock.o \
	embed/tneo/thread.o embed/tneo/tn_backend.o embed/tneo/utils.o

HEADER_embed += embed/tneo/hr_time.h embed/tneo/lock.h \
	embed/tneo/thread.h embed/tneo/tn_backend.h

