#
#   Carbon framework example makefile
#
#   Copyright (c) 2016 Softland. All rights reserved.
#   Licensed under the Apache License, Version 2.0
#
#   Revision history:
#
#   Revision 1.0, 02.11.2016 17:58:26
#	Initial revision.
#
#   make [CROSS_COMPILE=<gcc-prefix>] [RELEASE=1]
#

PROGRAM = empty

OBJ = empty.o

all: carbon_dep $(PROGRAM)

include ../../tool/pkgrules.mak
