#
#   Carbon Shell Executor makefile
#
#   Copyright (c) 2016 Softland. All rights reserved.
#   Licensed under the Apache License, Version 2.0
#
#   Revision history:
#
#   Revision 1.0, 05.08.2016 13:04:11
#	Initial revision.
#
#   make [CROSS_COMPILE=<gcc-prefix->] [RELEASE=1]
#

PROGRAM = shell_execute

OBJ = shell_execute.o
HEADER =

DEPS = $(HEADER)

all: carbon_dep $(PROGRAM)

include ../../tool/pkgrules.mak



