#
#   Carbon Framework example makefile
#   Example kernel driver
#
#   Copyright (c) 2017 Softland. All rights reserved.
#   Licensed under the Apache License, Version 2.0
#
#   Revision history:
#
#   Revision 1.0, 27.01.2017 18:25:37
#	Initial revision.
#
#

obj-m := example.o
example-objs := example_main.o
