
OBJ += vep/vep_container.o vep/vep_packet.o vep/vep_server.o \
	vep/vep_server_thread.o vep/packet_system.o \
	vep/vep_container_atomic.o vep/sys_responder.o \

DEPS += vep/vep.h vep/vep_container.h vep/vep_packet.h vep/vep_server.h \
	vep/vep_server_thread.h vep/packet_system.h vep/vep_container_atomic.h \
	vep/sys_responder.h

