#!/bin/sh
#
#	all clean '' install
set -e

TARGET=build_lib_static

for opt in "$@"; do
    if [ "x$opt" = "xclean" ]; then
	TARGET="clean distclean"
	break
    fi
    if [ "x$opt" = "xinstall" ]; then
	TARGET="install_include install_lib_static"
    fi
done

make ${TARGET} 
