
OBJ_embed += embed/freertos/hr_time.o embed/freertos/os_backend.o \
		embed/freertos/lock.o embed/freertos/thread.o embed/freertos/utils.o

HEADER_embed += embed/freertos/hr_time.h embed/freertos/os_backend.h \
		embed/freertos/lock.h embed/freertos/thread.h

