#
#   Carbon framework makefile
#
#   Copyright (c) 2010-2016 Softland. All rights reserved.
#   Licensed under the Apache License, Version 2.0
#
#   Revision history:
#
#   Revision 1.0, 14.06.2010
#	Initial revision.
#
#   Revision 2.0, 26.02.2015
#	Moved from 'c' to 'cpp'
#
#   Revision 3.0, 02.11.2016, 17:34:27
#	Added net_media library    
#
#   make [RELEASE=1] [all|clean|rebuild]
#

DIRS = shell carbon module

include ../tool/multidir.mak

